services:
  - type: web
    name: plant-system
    env: node
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: ONENET_PRODUCT_ID
        sync: false
      - key: ONENET_DEVICE_NAME
        sync: false
      - key: ONENET_ACCESS_KEY
        sync: false
      - key: PORT
        value: 10000
